"use client";

import Link from "next/link";
import Image from "next/image";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Brand from "./Brand";
import LanguageToggle from "./LanguageToggle";
import { useLanguage } from "./LanguageProvider";

type Student = { studentId: string; name: string; isGuest?: boolean };
type Qa = { id: number; studentName: string; question: string; imageKey?: string | null; answer?: string | null; createdAt: string };
type Resource = { id: number; title: string; filename: string; size: number; createdAt: string };

export default function StudentPortal() {
  const router = useRouter();
  const { language } = useLanguage(); const zh = language === "zh";
  const [student, setStudent] = useState<Student | null>(null); const [loginMode, setLoginMode] = useState<"registered" | "guest">("registered"); const [studentId, setStudentId] = useState(""); const [password, setPassword] = useState(""); const [guestName, setGuestName] = useState(""); const [code, setCode] = useState("");
  const [qa, setQa] = useState<Qa[]>([]); const [resources, setResources] = useState<Resource[]>([]); const [question, setQuestion] = useState(""); const [image, setImage] = useState<File | null>(null); const [error, setError] = useState("");
  const load = useCallback(async () => { const [session, questions, files] = await Promise.all([fetch("/api/student/session").then(r=>r.json()),fetch("/api/qa").then(r=>r.json()),fetch("/api/resources").then(r=>r.json())]); setStudent(session.student || null); setQa(questions.items || []); setResources(files.resources || []); }, []);
  useEffect(() => { const timer=window.setTimeout(()=>{void load();},0); return()=>window.clearTimeout(timer); }, [load]);
  async function login(e: FormEvent) { e.preventDefault(); setError(""); const guest=loginMode==="guest"; const r=await fetch(guest?"/api/student/guest-login":"/api/student/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(guest?{studentId,name:guestName}:{studentId,password})}); const d=await r.json(); if(!r.ok){setError(d.error);return;} setStudent(d.student); setPassword(""); const next=new URLSearchParams(window.location.search).get("next"); if(next?.startsWith('/')) router.push(next); else await load(); }
  async function ask(e: FormEvent) { e.preventDefault(); const form=new FormData(); form.set("question",question); if(image) form.set("image",image); const r=await fetch("/api/qa",{method:"POST",body:form}); const d=await r.json(); if(!r.ok){setError(d.error);return;} setQuestion(""); setImage(null); await load(); }
  if (!student) return <main className="student-portal"><header className="simple-header"><Brand /><LanguageToggle /></header><section className="portal-card student-login-card"><div className="student-login-tabs" role="tablist" aria-label={zh?"选择登录方式":"Choose sign-in method"}><button type="button" className={loginMode==="registered"?"active":""} aria-pressed={loginMode==="registered"} onClick={()=>{setLoginMode("registered");setError("");}}>{zh?"注册学生":"Registered student"}</button><button type="button" className={loginMode==="guest"?"active":""} aria-pressed={loginMode==="guest"} onClick={()=>{setLoginMode("guest");setError("");}}>{zh?"旁听生":"Auditing student"}</button></div><div className="student-login-heading"><span className="tiny-label">{zh?"学生入口":"Student access"}</span><h1>{loginMode==="registered"?(zh?"注册学生登录":"Registered student login"):(zh?"旁听生进入":"Auditing student access")}</h1><p>{loginMode==="registered"?(zh?"请使用学号和初始密码登录。初始密码为学号 + 2605（例如：学号 24001001，密码 240010012605）。":"Sign in with your student ID and initial password. Your initial password is your student ID + 2605 (for example: student ID 24001001, password 240010012605)."):(zh?"旁听生无需密码，请填写学号和姓名。提交测验后，排行榜只展示姓名。":"No password is required for auditing students. Enter your student ID and name; only your name will appear on the leaderboard.")}</p></div><form className="student-login-form" onSubmit={login}><label><span>{zh?"学号":"Student ID"}</span><input value={studentId} onChange={e=>setStudentId(e.target.value)} autoComplete="username" placeholder={zh?"请输入学号":"Enter your student ID"} autoFocus required /></label>{loginMode==="registered"?<label><span>{zh?"密码":"Password"}</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" placeholder={zh?"请输入初始密码":"Enter your initial password"} required /></label>:<label><span>{zh?"姓名":"Name"}</span><input value={guestName} onChange={e=>setGuestName(e.target.value)} autoComplete="name" maxLength={40} placeholder={zh?"请输入姓名（排行榜将显示此姓名）":"Enter your name (shown on the leaderboard)"} required /></label>}{error&&<div className="error-box">{error}</div>}<button className="primary-button wide">{loginMode==="registered"?(zh?"登录":"Sign in"):(zh?"以旁听生身份进入":"Continue as auditing student")}</button></form></section></main>;
  return <main className="student-portal"><header className="simple-header"><Brand /><div className="header-actions"><span>{student.name}</span><LanguageToggle /><button className="secondary-button" onClick={async()=>{await fetch('/api/student/logout',{method:'POST'});setStudent(null);}}>{zh?"退出":"Sign out"}</button></div></header><section className="portal-grid"><article className="portal-card"><h2>{zh?"进入测验":"Join a quiz"}</h2><form onSubmit={e=>{e.preventDefault();if(code.trim()) router.push(`/quiz/${encodeURIComponent(code.trim().toUpperCase())}`);}}><label>{zh?"测验代码":"Quiz code"}<input value={code} onChange={e=>setCode(e.target.value)} /></label><button className="primary-button wide">{zh?"开始答题":"Start quiz"}</button></form></article><article className="portal-card"><h2>{zh?"提出问题":"Ask a question"}</h2><form onSubmit={ask}><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder={zh?"输入问题":"Type your question"} required/><input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>setImage(e.target.files?.[0]||null)}/><button className="primary-button">{zh?"提交问题":"Submit"}</button></form></article></section><section className="portal-grid"><article className="portal-card"><h2>{zh?"课程问答":"Course Q&A"}</h2>{qa.length===0?<p>{zh?"暂无问题":"No questions yet"}</p>:qa.map(item=><div className="qa-item" key={item.id}><b>{item.studentName}</b><p>{item.question}</p>{item.imageKey&&<Image src={`/api/qa/${item.id}/image`} alt="Question attachment" width={640} height={420} unoptimized/>}<div>{item.answer?<>A: {item.answer}</>:<em>{zh?"等待教师回答":"Waiting for answer"}</em>}</div></div>)}</article><article className="portal-card"><h2>{zh?"课程资料":"Course resources"}</h2>{resources.length===0?<p>{zh?"暂无资料":"No resources yet"}</p>:resources.map(item=><Link className="resource-row" href={`/api/resources/${item.id}/download`} key={item.id}><b>{item.title}</b><span>{item.filename} · {(item.size/1024/1024).toFixed(1)} MB</span></Link>)}</article></section></main>;
}
