"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import Image from "next/image";
import { useLanguage } from "./LanguageProvider";

type RosterPreview = { token:string; total:number; add:Array<{studentId:string;name:string}>; update:Array<{studentId:string;name:string;previousName:string}>; deactivate:Array<{studentId:string;name:string}>; unchanged:number };
type Qa = { id:number; studentId:string; studentName:string; question:string; imageKey?:string|null; answer?:string|null };
type Resource = { id:number; title:string; filename:string; size:number };

export default function TeacherTools() {
  const { language } = useLanguage(); const zh=language==="zh";
  const [preview,setPreview]=useState<RosterPreview|null>(null); const [qa,setQa]=useState<Qa[]>([]); const [resources,setResources]=useState<Resource[]>([]); const [message,setMessage]=useState("");
  const load=useCallback(async()=>{const [q,r]=await Promise.all([fetch('/api/teacher/qa').then(x=>x.json()),fetch('/api/teacher/resources').then(x=>x.json())]);setQa(q.items||[]);setResources(r.resources||[]);},[]);
  useEffect(()=>{void load();},[load]);
  async function uploadRoster(e:FormEvent<HTMLFormElement>){e.preventDefault();setMessage("");const r=await fetch('/api/teacher/roster/preview',{method:'POST',body:new FormData(e.currentTarget)});const d=await r.json();if(!r.ok){setMessage(d.error);return;}setPreview(d.preview);}
  async function confirmRoster(){if(!preview||!window.confirm(zh?'确认执行名单同步？未出现在新名单中的账号会被停用，但历史成绩会保留。':'Apply this roster sync? Missing accounts will be deactivated, while historical results stay intact.'))return;const r=await fetch('/api/teacher/roster/confirm',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:preview.token})});const d=await r.json();if(!r.ok){setMessage(d.error);return;}setPreview(null);setMessage(zh?`同步完成：${d.result.active} 个有效账号`:`Roster synced: ${d.result.active} active accounts`);}
  async function answer(id:number,answer:string){const r=await fetch(`/api/teacher/qa/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({answer})});if(r.ok)await load();}
  async function uploadResource(e:FormEvent<HTMLFormElement>){e.preventDefault();const formElement=e.currentTarget;const r=await fetch('/api/teacher/resources',{method:'POST',body:new FormData(formElement)});const d=await r.json();if(!r.ok){setMessage(d.error);return;}formElement.reset();await load();}
  return <section className="teacher-tools"><article className="tool-card"><h2>{zh?'学生名单与账号':'Roster and accounts'}</h2><p>{zh?'上传含“学号”和“姓名”列的 Excel。系统先显示变更，确认后新增账号并停用名单外账号。初始密码为学号加 2605。':'Upload an Excel file with Student ID and Name columns. Review changes before applying. Initial password is the student ID plus 2605.'}</p><form onSubmit={uploadRoster}><input name="file" type="file" accept=".xls,.xlsx" required/><button className="primary-button">{zh?'预览名单变更':'Preview roster changes'}</button></form>{message&&<div className="notice-box">{message}</div>}{preview&&<div className="sync-preview"><b>{zh?'待确认变更':'Changes awaiting confirmation'}</b><p>{zh?'名单总数':'Roster total'}: {preview.total} · {zh?'新增':'Add'}: {preview.add.length} · {zh?'更新':'Update'}: {preview.update.length} · {zh?'停用':'Deactivate'}: {preview.deactivate.length} · {zh?'不变':'Unchanged'}: {preview.unchanged}</p><details><summary>{zh?'查看详细变更':'View details'}</summary>{preview.add.map(x=><div key={'a'+x.studentId}>+ {x.studentId} {x.name}</div>)}{preview.update.map(x=><div key={'u'+x.studentId}>~ {x.studentId} {x.previousName} → {x.name}</div>)}{preview.deactivate.map(x=><div key={'d'+x.studentId}>− {x.studentId} {x.name}</div>)}</details><button className="primary-button" onClick={confirmRoster}>{zh?'管理员确认并执行':'Confirm and apply'}</button></div>}</article><article className="tool-card"><h2>{zh?'学生问答':'Student Q&A'}</h2>{qa.length===0?<p>{zh?'暂无问题':'No questions yet'}</p>:qa.map(item=><div className="qa-item" key={item.id}><b>{item.studentName} · {item.studentId}</b><p>{item.question}</p>{item.imageKey&&<Image src={`/api/qa/${item.id}/image`} alt="Question attachment" width={640} height={420} unoptimized/>}<textarea defaultValue={item.answer||''} id={`answer-${item.id}`} placeholder={zh?'输入回答':'Write an answer'}/><button className="secondary-button" onClick={()=>answer(item.id,(document.getElementById(`answer-${item.id}`) as HTMLTextAreaElement).value)}>{zh?'保存回答':'Save answer'}</button></div>)}</article><article className="tool-card"><h2>{zh?'课程资料库':'Course library'}</h2><form onSubmit={uploadResource}><label>{zh?'资料标题':'Title'}<input name="title"/></label><input name="file" type="file" accept=".ppt,.pptx,.pdf,.doc,.docx,.xls,.xlsx,.md,.markdown,.jpg,.jpeg,.png" required/><small>{zh?'单个文件最大 10 MB':'Maximum file size: 10 MB'}</small><button className="primary-button">{zh?'上传资料':'Upload resource'}</button></form>{resources.map(item=><div className="resource-row" key={item.id}><span><b>{item.title}</b><small>{item.filename} · {(item.size/1024/1024).toFixed(1)} MB</small></span><button onClick={async()=>{if(confirm(zh?'删除这份资料？':'Delete this resource?')){await fetch(`/api/teacher/resources/${item.id}`,{method:'DELETE'});await load();}}}>{zh?'删除':'Delete'}</button></div>)}</article></section>;
}
